version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "covid19-chatbot-2nd"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1x72hebufon8b"
s3_prefix = "covid19-chatbot-2nd"
region = "ap-northeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
